### ISSUE TITLE
유튜브 공식 카테고리 분류

### ISSUE THREAD

**Issue by gravityfalls0116** [MangoSteen0903/Youtube-Trend-Analysis-Project#11]
category_list={
    1:'Film & Animation',
    2:'Autos & Vehicles',
    10:"Music",
    15:"Pets & Animals",
    17:"Sports",
    18:"Short Movies",
    19:"Travel & Events",
    20:"Gaming",
    21:"Videoblogging",
    22:"People & Blogs",
    23:"Comedy",
    24:"Entertainment",
    25:"News & Politics",
    26:"Howto & Style",
    27:"Education",
    28:"Science & Technology",
    30:"Movies",
    31:"Anime/Animation",
    32:"Action/Adventure",
    33:"Classics",
    34:"Comedy",
    35:"Documentary",
    36:"Drama",
    37:"Family",
    38:"Foreign",
    39:"Horror",
    40:"Sci-Fi/Fantasy",
    41:"Thriller",
    42:"Shorts",
    43:"Shows",
    44:"Trailers"
}

<img width="640" alt="스크린샷 2021-07-11 오후 2 31 21" src="https://user-images.githubusercontent.com/33304970/125183887-cd094880-e254-11eb-9eda-2cff05122c69.png">

category 공식 분류를 이용하여 수치화한 결과 화면이다.
상위 10개 category를 기반으로 카테고리의 갯수를 축소하는 과정을 진행하였다.

결과
Music
Sports
News
Education: Howto & Style
Entertainment: Comedy, Shows, Family, Travel & Events, Drame
IT: Auto & Vehicle, Science & Technology
Game
People & Blog : V-log, pet
Flim- Action, Anime, Thriller, Sci-Fi/Fantasy, Trailers, Movies, Short Movies
shorts

**Comment by Heojiyeon** [comment]
0711 완료
